name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest tests/
      
      - name: Deploy to Heroku (if tests pass)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set this in GitHub Secrets
        run: |
          git remote add heroku https://git.heroku.com/<your-heroku-app-name>.git
          git push heroku main
